### ISSUE TITLE
énoncé exercice 6 à revoir

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/parcours_r_socle_preparation_des_donnees#15]
https://mtes-mct.github.io/parcours-r/m2/manipuler-plusieurs-tables.html#exercices

**Comment by jengelaere** [comment]
Il manquait surement un peu de contexte à l'exercice (devenu https://mtes-mct.github.io/parcours_r_socle_preparation_des_donnees/manipuler-plusieurs-tables.html#exercice-5)
Réglé dans savoir faire par le [commit 1cd6f558](https://github.com/MTES-MCT/savoirfR/commit/1cd6f55844d2aa92a225076cae7ee290b760d326#diff-cfcf8a571ff4826001156091cccbd8927cb127d10f2261d61dc473a36622b745).
